version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: eslint-plugin-simple-import-sort
    versions:
    - "> 5.0.3"
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.11.0
    - 0.12.0
    - 0.12.1
    - 0.12.2
    - 1.0.0
    - 1.1.0
    - 1.1.1
    - 1.2.0
    - 1.3.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: react-icons
    versions:
    - 4.1.0
