// When changing these colours, make sure to update the ones in colors.sass;
export const white = `#F7F7F7`;
export const translucentWhite = `rgba(247, 247, 247, 0.8)`;
export const green = `#4FC77B`;
export const lightEmerald = `#35AE9E`;
export const emerald = `#3F8F85`;
export const translucentEmerald = `rgba(63, 143, 133, 0.7)`;
export const lightGrey = `#E9E9E9`;
export const grey = `#D2D4C8`;
export const darkGrey = `#4A4A4A`;
export const black = `#3A3A3A`;
